[tool.poetry]
name = "qd"
version = "0.1.0"
description = ""
authors = ["Muntaser Abukhadijah <mabukhad@amazon.com>"]
readme = "README.md"
requires-python = ">=3.9"

[tool.poetry.dependencies]
python = ">=3.9"
fastapi = ">=0.115.8,<0.116.0"
uvicorn = ">=0.34.0,<0.35.0"
jinja2 = ">=3.1.5,<4.0.0"
python-multipart = ">=0.0.20,<0.0.21"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py37']

[tool.isort]
profile = "black"
line_length = 88
