[project]
name = "qd"
version = "0.1.0"
description = ""
authors = [
    {name = "Muntaser Abukhadijah",email = "mabukhad@amazon.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 88
target-version = ['py37']

[tool.isort]
profile = "black"
line_length = 88
