services:
  - type: web
    name: qd-app
    env: python
    buildCommand: poetry install --no-root
    startCommand: poetry run uvicorn main_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
